### ISSUE TITLE
Is stride supported?

### ISSUE THREAD

**Issue by guigrpa** [swillner/netcdf4-js#10]
The link in your README (https://www.unidata.ucar.edu/software/netcdf/docs/programming_notes.html#specify_hyperslab) talks about a stride. Is it possible to use strides with your library?

Thanks!

**Comment by swillner** [comment]
unfortunately strides are not supported yet, but I will implement support for them soon. thanks for pointing them out!

**Comment by guigrpa** [comment]
If you think it's relatively straightforward and I can be of any help, please let me know!

**Comment by swillner** [comment]
that would be great! it should be pretty straightforward. we would probably need new functions `readStridedSlice`/`'writeStridedSlice` working very similar to `readSlice`/`'writeSlice`, but using `nc_get_vars` instead of `nc_get_vara`. maybe you also have a good idea of what a good function signature would look like there (or we just use `readStridedSlice(pos1, size1, stride1, ...)` as for `readSlice`)...
